Repository jobrunr/jobrunr, pull requests merged in 2025-04, with the labels that each got.

#1226 MongoDB Usage Index improvement
  core/src/main/java/org/jobrunr/storage/nosql/mongo/MongoDBStorageProvider.java
Labels: cla-signed

#1228 Improve Progress bar
  core/src/main/java/org/jobrunr/jobs/context/JobDashboardProgressBar.java
Labels: cla-signed

#1229 cleanup creation of datasources in storage provider tests
  core/src/test/java/org/jobrunr/storage/sql/SqlStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/db2/AbstractDB2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/db2/DB2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/db2/DB2TablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/AgroalH2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/CommonsDbcpAutoCommitFalseH2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/CommonsDbcpH2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/HikariH2AutoCommitFalseStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/HikariH2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/NativePoolH2TablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/TomcatJdbcPoolAutoCommitFalseH2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/TomcatJdbcPoolH2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mariadb/AbstractMariaDbStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mariadb/MariaDbStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mariadb/MariaDbTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mysql/AbstractMySQLStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mysql/MySQLStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mysql/MySQLTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/AbstractOracleStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/OracleStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/OracleTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/postgres/AbstractPostgresStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/postgres/CloudSqlPostgresStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/postgres/PostgresStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/postgres/PostgresTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/sqlite/SqLiteStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/AbstractSQLServerStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/SQLServerStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/SQLServerTablePrefixStorageProviderTest.java
Labels: cla-signed

#1231 Fix progress bar
  core/src/main/java/org/jobrunr/jobs/context/JobDashboardProgressBar.java
  core/src/test/java/org/jobrunr/jobs/context/JobDashboardProgressBarTest.java
Labels: cla-signed, v8

#1232 Add architecture test to ensure classes named Abstract have abstract modifier
  core/src/main/java/org/jobrunr/dashboard/sse/AbstractObjectSseExchange.java
  core/src/test/java/org/jobrunr/architecture/ClassNamesTest.java
  core/src/testFixtures/java/org/junit/jupiter/extension/ForAllSubclassesExtension.java
Labels: cla-signed

#1233 Add and test existing 404s for the Webserver API
  core/src/main/java/org/jobrunr/dashboard/JobRunrApiHandler.java
  core/src/main/java/org/jobrunr/storage/InMemoryStorageProvider.java
  core/src/test/java/org/jobrunr/storage/ThreadSafeStorageProviderTest.java
  core/src/testFixtures/java/org/jobrunr/dashboard/JobRunrDashboardWebServerTest.java
  core/src/testFixtures/java/org/jobrunr/storage/StorageProviderTest.java
Labels: cla-signed, v8

#1234 Update dependencies
  core/build.gradle
  core/src/main/resources/org/jobrunr/dashboard/frontend/package-lock.json
  core/src/main/resources/org/jobrunr/dashboard/frontend/package.json
  core/src/test/java/org/jobrunr/storage/sql/db2/DB2TablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/h2/NativePoolH2TablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mariadb/MariaDbTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mysql/MySQLTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/AbstractOracleStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/OracleStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/OracleTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/postgres/PostgresTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/SQLServerTablePrefixStorageProviderTest.java
  core/src/test/java/org/jobrunr/utils/JarUtilsTest.java
  framework-support/jobrunr-micronaut-feature/build.gradle
  framework-support/jobrunr-quarkus-extension/quarkus-jobrunr-deployment/build.gradle
  framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/build.gradle
  framework-support/jobrunr-quarkus-extension/tests/build.gradle
  framework-support/jobrunr-spring-boot-2-starter/build.gradle
  framework-support/jobrunr-spring-boot-3-starter/build.gradle
  language-support/jobrunr-kotlin-19-support/build.gradle
  language-support/jobrunr-kotlin-20-support/build.gradle
  language-support/jobrunr-kotlin-21-support/build.gradle
  platform/build.gradle
  tests/e2e-ui/build.gradle
  tests/e2e-vm-jdk/build.gradle
Labels: cla-signed

#1235 Improve build
  .drone.yml
  build.gradle
  core/build.gradle
  framework-support/jobrunr-quarkus-extension/quarkus-jobrunr/build.gradle
  framework-support/jobrunr-spring-boot-2-starter/build.gradle
  framework-support/jobrunr-spring-boot-3-starter/build.gradle
  language-support/jobrunr-kotlin-19-support/build.gradle
  language-support/jobrunr-kotlin-20-support/build.gradle
  language-support/jobrunr-kotlin-21-support/build.gradle
  tests/e2e-ui/build.gradle
  tests/e2e-vm-jdk/build.gradle
Labels: cla-signed

#1243 From Pro: Fix #550 UI returns 404 after filtering on job signature
  core/src/main/java/org/jobrunr/dashboard/server/http/StaticFileHttpHandler.java
  core/src/test/java/org/jobrunr/dashboard/server/http/StaticFileHttpHandlerTest.java
Labels: cla-signed

#1225 Schedule recurring jobs ahead of time
  core/src/main/java/org/jobrunr/jobs/RecurringJob.java
  core/src/main/java/org/jobrunr/jobs/states/ScheduledState.java
  core/src/main/java/org/jobrunr/server/tasks/zookeeper/ProcessRecurringJobsTask.java
  core/src/main/java/org/jobrunr/storage/InMemoryStorageProvider.java
  core/src/main/java/org/jobrunr/storage/StorageProvider.java
  core/src/main/java/org/jobrunr/storage/ThreadSafeStorageProvider.java
  core/src/main/java/org/jobrunr/storage/nosql/mongo/MongoDBStorageProvider.java
  core/src/main/java/org/jobrunr/storage/nosql/mongo/MongoUtils.java
  core/src/main/java/org/jobrunr/storage/nosql/mongo/mapper/JobDocumentMapper.java
  core/src/main/java/org/jobrunr/storage/sql/common/DefaultSqlStorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/common/JobTable.java
  core/src/main/java/org/jobrunr/utils/CollectionUtils.java
  core/src/test/java/org/jobrunr/dashboard/FrontEndDevelopment.java
  core/src/test/java/org/jobrunr/jobs/RecurringJobTest.java
  core/src/test/java/org/jobrunr/scheduling/BackgroundJobByJobLambdaTest.java
  core/src/test/java/org/jobrunr/server/tasks/AbstractTaskTest.java
  core/src/test/java/org/jobrunr/server/tasks/zookeeper/ProcessRecurringJobsTaskTest.java
  core/src/test/java/org/jobrunr/utils/CollectionUtilsTest.java
  core/src/testFixtures/java/org/jobrunr/jobs/JobAssert.java
  core/src/testFixtures/java/org/jobrunr/storage/StorageProviderTest.java
  core/src/testFixtures/java/org/mockito/InstantMocker.java
Labels: wontfix, cla-signed, breaking
