Repository jobrunr/jobrunr, pull requests merged in 2025-06, with the labels that each got.

#1285 Move from Drone to Woodpecker
  .drone.yml
  .woodpecker/default.yaml
  .woodpecker/release.yaml
  .woodpecker/sonar.yaml.todo
  BuildDockerfile
  build.gradle
  core/src/testFixtures/java/org/jobrunr/utils/CIInfo.java
  platform/build.gradle
  settings.gradle
  tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/GradleBuildAndTestContainer.java
  tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/MavenBuildAndTestContainer.java
Labels: cla-signed

#1287 Try to fix gradle build cache
  .woodpecker/default.yaml
  .woodpecker/release.yaml
  core/build.gradle
  core/src/test/java/org/jobrunr/storage/sql/oracle/OracleStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/oracle/OracleTablePrefixStorageProviderTest.java
  framework-support/jobrunr-spring-boot-3-starter/build.gradle
  platform/build.gradle
Labels: cla-signed

#1291 Fix unclosed resultset on startup.
  CONTRIBUTING.md
  core/src/main/java/org/jobrunr/storage/sql/common/DatabaseCreator.java
Labels: enhancement, cla-signed, v8

#1293 Remove fail-fast option to detect all failures at once
  .woodpecker/default.yaml
Labels: cla-signed

#1296 Remove Kotlin 1.9 support
  settings.gradle
Labels: cla-signed

#1300 Fix jobs-view.js fetch race condition
  core/build.gradle
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/jobs/jobs-view.js
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/AbstractSQLServerStorageProviderTest.java
  core/src/test/resources/container-license-acceptance.txt
  platform/build.gradle
  settings.gradle
  tests/e2e-ui/src/test/java/org/jobrunr/tests/e2e/AbstractDashboardActionsE2ETest.java
  tests/e2e-vm-jdk/.mvn/wrapper/maven-wrapper.jar
  tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/MavenBuildAndTestContainer.java
Labels: cla-signed

#1301 Prep for release
  .woodpecker/release.yaml
  build.gradle
  platform/build.gradle
  tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/GradleBuildAndTestContainer.java
Labels: cla-signed

#1303 Merge master into v8
  .woodpecker/release.yaml
  build.gradle
Labels: cla-signed

#1304 remove README.md alter by build to prep release
  .woodpecker/release.yaml
Labels: cla-signed

#1305 Merge Master in v8
  .woodpecker/release.yaml
Labels: cla-signed

#1309 Add notification center
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/CarbonIntensityApiErrorProblem.java
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/CarbonIntensityApiErrorProblemHandler.java
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/CpuAllocationIrregularityProblem.java
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/PollIntervalInSecondsTimeBoxIsTooSmallProblem.java
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/Problem.java
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/SevereJobRunrExceptionProblem.java
  core/src/main/java/org/jobrunr/utils/InstantUtils.java
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/carbon-intensity-api-error-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/cpu-allocation-irregularity-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/dismissible-notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/job-not-found-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/jobrunr-api-notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/new-jobrunr-version-available.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/poll-interval-timebox-is-too-small-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/severe-jobrunr-exception-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/top-app-bar-notification-center.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/overview/overview.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/overview/problems/carbon-intensity-api-error-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/overview/problems/dismissible-problem-notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/overview/problems/jobrunr-api-notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/overview/problems/problem-notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/overview/problems/problems-notifications.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/ui/ClickAwayPopper.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/layouts/Admin.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/layouts/TopAppBar.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/utils/helper-functions.js
  core/src/test/java/org/jobrunr/dashboard/FrontEndDevelopment.java
  core/src/test/java/org/jobrunr/dashboard/ui/model/problems/CarbonIntensityApiErrorProblemHandlerTest.java
  core/src/testFixtures/resources/dashboard/api/problems-job-not-found.json
  core/src/testFixtures/resources/dashboard/api/problems-severe-jobrunr-problem.json
  tests/e2e-ui/src/test/java/org/jobrunr/tests/e2e/AbstractDashboardActionsE2ETest.java
  tests/e2e-ui/src/test/java/org/jobrunr/tests/e2e/AbstractPlaywrightE2ETest.java
Labels: cla-signed

#1313 add carbon intensity api response code + message in the notification centre
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/CarbonIntensityApiErrorProblem.java
  core/src/main/java/org/jobrunr/dashboard/ui/model/problems/CarbonIntensityApiErrorProblemHandler.java
  core/src/main/java/org/jobrunr/server/carbonaware/CarbonIntensityApiClient.java
  core/src/main/java/org/jobrunr/server/carbonaware/CarbonIntensityApiClientException.java
  core/src/main/java/org/jobrunr/server/carbonaware/CarbonIntensityForecast.java
  core/src/main/java/org/jobrunr/server/dashboard/CarbonIntensityApiErrorNotification.java
  core/src/main/java/org/jobrunr/server/dashboard/mappers/CarbonIntensityApiErrorNotificationMapper.java
  core/src/main/java/org/jobrunr/server/tasks/zookeeper/ProcessCarbonAwareAwaitingJobsTask.java
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/carbon-intensity-api-error-problem.js
  core/src/test/java/org/jobrunr/dashboard/FrontEndDevelopment.java
  core/src/test/java/org/jobrunr/dashboard/ui/model/problems/CarbonIntensityApiErrorProblemHandlerTest.java
  core/src/test/java/org/jobrunr/server/carbonaware/AbstractCarbonIntensityApiClientTest.java
  core/src/test/java/org/jobrunr/server/carbonaware/CarbonIntensityForecastTest.java
Labels: cla-signed

#1315 Chore/carbon intensity region endpoint update
  core/src/main/java/org/jobrunr/server/carbonaware/CarbonAwareJobProcessingConfigurationReader.java
  core/src/test/java/org/jobrunr/server/carbonaware/AbstractCarbonIntensityApiClientTest.java
  core/src/test/java/org/jobrunr/server/carbonaware/CarbonAwareApiWireMockExtension.java
  core/src/test/java/org/jobrunr/server/carbonaware/CarbonAwareJobProcessingConfigurationTest.java
Labels: cla-signed

#1316 Fix possible NPE when processing carbon aware jobs
  core/src/main/java/org/jobrunr/server/tasks/zookeeper/ProcessCarbonAwareAwaitingJobsTask.java
  core/src/test/java/org/jobrunr/server/tasks/zookeeper/ProcessCarbonAwareAwaitingJobsTaskTest.java
Labels: cla-signed

#1314 Drop support for Spring Boot 2
  framework-support/jobrunr-spring-boot-2-starter/build.gradle
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/scheduling/AsyncJobPostProcessor.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/scheduling/JobInterceptor.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/scheduling/RecurringJobPostProcessor.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrProperties.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrStarter.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/health/JobRunrHealthIndicator.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/metrics/JobRunrMetricsAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrDocumentDBStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrInMemoryStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrSqlStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/resources/META-INF/spring.factories
  framework-support/jobrunr-spring-boot-2-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/scheduling/AsyncJobPostPostProcessorTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/scheduling/RecurringJobPostProcessorTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/CGLibJobDetailsPostProcessorTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/JobRunrAutoConfigurationTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/Mocks.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/health/JobRunrHealthIndicatorTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/metric/JobRunrMetricsAutoConfigurationTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/resources/logback.xml
  framework-support/jobrunr-spring-boot-2-starter/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  settings.gradle
Labels: cla-signed, v8, breaking

#1318 Align frontend components with JobRunr Pro
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/ProblemsContext.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/jobs/jobs-table.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/jobs/jobs-view.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/carbon-intensity-api-error-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/cpu-allocation-irregularity-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/dismissible-notification.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/poll-interval-timebox-is-too-small-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/severe-jobrunr-exception-problem.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/notifications/top-app-bar-notification-center.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/utils/version-footer.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/contexts/JobRunrInfoContext.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/layouts/Admin.js
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/layouts/TopAppBar.js
Labels: cla-signed
