Repository jobrunr/jobrunr, pull requests merged in 2025-05, with the labels that each got.

#1249 Fix NPE during metric collection (fixes #1247)
  core/build.gradle
  core/src/main/java/org/jobrunr/server/metrics/BackgroundJobServerMetricsBinder.java
  core/src/test/java/org/jobrunr/server/metrics/BackgroundJobServerMetricsBinderTest.java
  core/src/testFixtures/java/io/instrument/MeterAssert.java
  core/src/testFixtures/java/org/jobrunr/JobRunrAssertions.java
Labels: cla-signed

#1251 Micrometer reporting improvements
  core/src/main/java/org/jobrunr/server/metrics/BackgroundJobServerMetricsBinder.java
  core/src/main/java/org/jobrunr/storage/metrics/StorageProviderMetricsBinder.java
  core/src/main/java/org/jobrunr/utils/resilience/CachedValue.java
  core/src/test/java/org/jobrunr/server/metrics/BackgroundJobServerMetricsBinderTest.java
  core/src/test/java/org/jobrunr/storage/metrics/StorageProviderMetricsBinderTest.java
  core/src/test/java/org/jobrunr/utils/resilience/CachedValueTest.java
  framework-support/jobrunr-quarkus-extension/tests/src/test/java/org/jobrunr/quarkus/it/JobRunrFunctionalityTest.java
Labels: cla-signed, v8, breaking

#1252 Align sql statement construct with JobRunr Pro
  core/src/main/java/org/jobrunr/storage/sql/common/BackgroundJobServerTable.java
  core/src/main/java/org/jobrunr/storage/sql/common/JobTable.java
  core/src/main/java/org/jobrunr/storage/sql/common/db/Dialect.java
  core/src/main/java/org/jobrunr/storage/sql/common/db/Sql.java
  core/src/main/java/org/jobrunr/storage/sql/common/db/SqlSpliterator.java
  core/src/main/java/org/jobrunr/storage/sql/common/db/SqlStatement.java
  core/src/main/java/org/jobrunr/storage/sql/db2/DB2Dialect.java
  core/src/main/java/org/jobrunr/storage/sql/db2/DB2StorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/h2/H2Dialect.java
  core/src/main/java/org/jobrunr/storage/sql/h2/H2StorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/oracle/OracleStorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/postgres/PostgresStorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/sqlite/SqLiteStorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/sqlserver/SQLServerDialect.java
  core/src/main/java/org/jobrunr/storage/sql/sqlserver/SQLServerStorageProvider.java
  core/src/test/java/org/jobrunr/storage/sql/SqlStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/common/db/SqlTest.java
  core/src/test/java/org/jobrunr/storage/sql/db2/DB2DialectTest.java
  core/src/test/java/org/jobrunr/storage/sql/db2/DB2StorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mariadb/MariaDbStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/mysql/MySQLStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/postgres/PostgresStorageProviderTest.java
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/SQLServerStorageProviderTest.java
Labels: cla-signed

#1254 Merge master into v8
  core/build.gradle
  core/src/main/java/org/jobrunr/dashboard/server/http/StaticFileHttpHandler.java
  core/src/main/java/org/jobrunr/server/metrics/BackgroundJobServerMetricsBinder.java
  core/src/test/java/org/jobrunr/dashboard/server/http/StaticFileHttpHandlerTest.java
  core/src/test/java/org/jobrunr/server/metrics/BackgroundJobServerMetricsBinderTest.java
  core/src/testFixtures/java/io/instrument/MeterAssert.java
  core/src/testFixtures/java/org/jobrunr/JobRunrAssertions.java
Labels: cla-signed

#1255 Reduce the amount of methods exposed by JobScheduler and JobRequestScheduler
  core/src/main/java/org/jobrunr/scheduling/AbstractJobScheduler.java
  core/src/main/java/org/jobrunr/scheduling/BackgroundJob.java
  core/src/main/java/org/jobrunr/scheduling/BackgroundJobRequest.java
  core/src/main/java/org/jobrunr/scheduling/JobRequestScheduler.java
  core/src/main/java/org/jobrunr/scheduling/JobScheduler.java
  core/src/main/java/org/jobrunr/utils/InstantUtils.java
  core/src/test/java/org/jobrunr/scheduling/AbstractJobSchedulerTest.java
  core/src/test/java/org/jobrunr/utils/InstantUtilsTest.java
Labels: cla-signed, v8

#1256 Add support for SLF4J Marker in JobRunr Dashboard.
  core/src/main/java/org/jobrunr/jobs/context/JobRunrDashboardLogger.java
  core/src/test/java/org/jobrunr/jobs/context/JobRunrDashboardLoggerTest.java
Labels: cla-signed

#1258 Drop `org` prefix from JobRunr's Spring properties
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrProperties.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/metrics/JobRunrMetricsAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrDocumentDBStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrInMemoryStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrSqlStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/JobRunrAutoConfigurationTest.java
  framework-support/jobrunr-spring-boot-2-starter/src/test/java/org/jobrunr/spring/autoconfigure/metric/JobRunrMetricsAutoConfigurationTest.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrProperties.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/metrics/JobRunrMetricsAutoConfiguration.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrDocumentDBStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrInMemoryStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-3-starter/src/main/java/org/jobrunr/spring/autoconfigure/storage/JobRunrSqlStorageAutoConfiguration.java
  framework-support/jobrunr-spring-boot-3-starter/src/test/java/org/jobrunr/spring/autoconfigure/JobRunrAutoConfigurationTest.java
  framework-support/jobrunr-spring-boot-3-starter/src/test/java/org/jobrunr/spring/autoconfigure/metric/JobRunrMetricsAutoConfigurationTest.java
  framework-support/jobrunr-spring-boot-3-starter/src/test/resources/application.properties
Labels: cla-signed, v8, breaking

#1259 Improve UUIDv7 test
  .drone.yml
  README.md
  core/src/test/java/org/jobrunr/storage/sql/sqlserver/AbstractSQLServerStorageProviderTest.java
  core/src/test/java/org/jobrunr/utils/uuid/UUIDv7FactoryTest.java
  core/src/test/resources/container-license-acceptance.txt
  core/src/test/resources/logback-test.xml
  core/src/testFixtures/java/io/micrometer/core/instrument/MeterAssert.java
  core/src/testFixtures/java/org/jobrunr/JobRunrAssertions.java
  tests/e2e-vm-jdk/.mvn/wrapper/maven-wrapper.jar
  tests/e2e-vm-jdk/.mvn/wrapper/maven-wrapper.properties
  tests/e2e-vm-jdk/gradle/wrapper/gradle-wrapper.jar
  tests/e2e-vm-jdk/gradle/wrapper/gradle-wrapper.properties
  tests/e2e-vm-jdk/gradlew
  tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/JdkTest.java
  tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/MavenBuildAndTestContainer.java
Labels: cla-signed

#1266 Try to Fix concurrent builds on Mac
  .drone.yml
  PrepareDockerfile
  core/src/main/java/org/jobrunr/dashboard/JobRunrApiHandler.java
Labels: cla-signed

#1271 Improve logging on Drone CI
  .drone.yml
  core/src/main/java/org/jobrunr/server/BackgroundJobServer.java
  core/src/main/java/org/jobrunr/server/ServerZooKeeper.java
  core/src/main/java/org/jobrunr/server/lifecycle/AbstractLifecycleLock.java
  core/src/main/java/org/jobrunr/server/lifecycle/BackgroundJobServerLifecycle.java
  core/src/main/java/org/jobrunr/server/lifecycle/BackgroundJobServerLifecycleEvent.java
  core/src/main/java/org/jobrunr/server/lifecycle/LifecycleChangeLock.java
  core/src/main/java/org/jobrunr/server/lifecycle/LifecycleReadLock.java
  core/src/test/java/org/jobrunr/architecture/ClassNamesTest.java
  core/src/test/java/org/jobrunr/server/tasks/zookeeper/ProcessRecurringJobsTaskTest.java
Labels: cla-signed

#1273 Add support for gradle build cache
  .drone.yml
  core/src/test/java/org/jobrunr/utils/GCUtils.java
  settings.gradle
Labels: cla-signed

#1268 [Dashboard] Add confirmation dialog for deleting recurring job
  core/src/main/java/org/jobrunr/jobs/states/StateName.java
  core/src/main/java/org/jobrunr/server/tasks/zookeeper/ProcessRecurringJobsTask.java
  core/src/main/java/org/jobrunr/storage/InMemoryStorageProvider.java
  core/src/main/java/org/jobrunr/storage/StorageProvider.java
  core/src/main/java/org/jobrunr/storage/ThreadSafeStorageProvider.java
  core/src/main/java/org/jobrunr/storage/nosql/mongo/MongoDBStorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/common/DefaultSqlStorageProvider.java
  core/src/main/java/org/jobrunr/storage/sql/common/JobTable.java
  core/src/main/resources/org/jobrunr/dashboard/frontend/src/components/recurring-jobs/recurring-jobs.js
  core/src/test/java/org/jobrunr/dashboard/FrontEndDevelopment.java
  core/src/test/java/org/jobrunr/server/tasks/zookeeper/ProcessRecurringJobsTaskTest.java
  core/src/testFixtures/java/org/jobrunr/storage/StorageProviderTest.java
Labels: cla-signed

#1275 Fix release pipeline
  .drone.yml
Labels: cla-signed

#1261 Allow to recover from `JobNotDeserializableException` and reduce stacktrace of orphaned job exception
  core/src/main/java/org/jobrunr/jobs/JobDetails.java
  core/src/main/java/org/jobrunr/jobs/JobParameter.java
  core/src/main/java/org/jobrunr/jobs/JobParameterNotDeserializableException.java
  core/src/main/java/org/jobrunr/jobs/exceptions/IllegalJobThreadStateException.java
  core/src/main/java/org/jobrunr/jobs/exceptions/JobParameterNotDeserializableException.java
  core/src/main/java/org/jobrunr/scheduling/exceptions/JobNotFoundException.java
  core/src/main/java/org/jobrunr/server/tasks/zookeeper/ProcessOrphanedJobsTask.java
  core/src/main/java/org/jobrunr/utils/GraalVMUtils.java
  core/src/main/java/org/jobrunr/utils/mapper/gson/JobParameterDeserializer.java
  core/src/main/java/org/jobrunr/utils/mapper/jackson/modules/JobParameterDeserializer.java
  core/src/main/java/org/jobrunr/utils/mapper/jsonb/adapters/JobDetailsAdapter.java
  core/src/test/java/org/jobrunr/jobs/JobDetailsTest.java
  core/src/test/java/org/jobrunr/scheduling/exceptions/JobNotFoundExceptionTest.java
  core/src/test/java/org/jobrunr/server/BackgroundJobServerTest.java
  core/src/test/java/org/jobrunr/server/tasks/zookeeper/ProcessOrphanedJobsTaskTest.java
  core/src/testFixtures/java/org/jobrunr/jobs/JobDetailsAssert.java
  core/src/testFixtures/java/org/jobrunr/jobs/mappers/JobMapperTest.java
  core/src/testFixtures/java/org/jobrunr/utils/mapper/AbstractJsonMapperTest.java
  language-support/jobrunr-kotlin-21-support/src/main/kotlin/org/jobrunr/kotlin/serialization/jobs/JobParameterNotDeserializableExceptionSerializer.kt
  language-support/jobrunr-kotlin-21-support/src/main/kotlin/org/jobrunr/kotlin/serialization/jobs/JobParameterSerializer.kt
  language-support/jobrunr-kotlin-21-support/src/main/kotlin/org/jobrunr/kotlin/utils/mapper/KotlinxSerializationModule.kt
Labels: cla-signed, v8, breaking
